captions = [
    "I'm not going to say the word I'm thinking of.",
    "I still wish we'd gotten a pool, instead of this ridiculous sculpture.",
    "So then I asked myself, what would Dr. Freud have done.",
    "It started when they moved in next door.",
    "The WiFi signal is stronger over here.",
    "I told him to think outside the box, but this is not what I had in mind.",
    "They said it was an 'open concept' apartment.",
    "It's the latest in eco-friendly transportation.",
    "Dinner parties just haven't been the same since.",
    "Believe it or not, it's a tax write-off.",
    "His version of 'working from home' is a bit different than mine.",
    "The homeowners association is going to have a field day with this.",
    "It's avant-garde, darling. You wouldn't understand.",
    "I preferred it when he was just into knitting.",
    "It's either a modern art installation or a very elaborate mouse trap.",
    "They never mentioned this scenario in the user manual.",
    "Well, at least it's a conversation starter.",
    "Trust me, it looked smaller in the catalog.",
    "You think this is something? Wait until you see the basement.",
    "I remember when this was just a one-penguin neighborhood.",
    "It's his solution to the morning commute.",
    "Suddenly, my yoga retreat doesn't seem so outlandish.",
    "They said to embrace change, but this feels a bit much.",
    "Apparently, this is 'Phase One'. I'm afraid to ask about Phase Two.",
    "Honestly, I miss the days when he just collected stamps.",
    "It's either the height of fashion or a cry for help.",
    "She said she wanted a home with character.",
    "I was aiming for minimalist, but I may have overshot.",
    "Last week, it was interpretive dance. This week? This.",
    "You'd think after three attempts, we'd have figured out flat-pack furniture."
]